import { useEffect, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Bot, Clock3, Route } from 'lucide-react'
import { api } from '../api/client'
import { useTenant } from '../context/TenantContext'
import { PageHeader } from '../components/PageHeader'
import { ErrorState, Loading } from '../components/AsyncState'
