import { Link } from 'react-router-dom'
import { CheckCircle2, FileSpreadsheet, FlaskConical } from 'lucide-react'
import { PageHeader } from '../components/PageHeader'
import { coveragePhases, workbookControls } from '../data/coverage'
import { Card, CardContent } from '@/components/ui/card'
